dist: xenial   # required for Python >= 3.7
language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.7.2 on macOS"
      os: osx
      python: 3.7
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.7.3 on Windows"
      os: windows
      python: 3.7
      language: shell
      before_install: choco install python --version 3.7.3
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial
    - name: "Python 3.6 on macOS"
      os: osx
      python: 3.6
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.6 on Windows"
      os: windows
      python: 3.6
      language: shell
      before_install: choco install python --version 3.6.7
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.5 on Linux"
      python: 3.5

install:
  - pip install -r requirements.txt
script:
  - pytest -v --cov-report term --cov=tests/
after_success:
  - codecov
deploy:
  provider: pypi
  user: langote.gopinath
  password:
    secure: qC9/51TMJyK7DC1Ewfc2+UemndTlFZumka5pZAgKT4r2l7fM8Lh4ccEzOV06LOhSOUpzZ0g+onpkPzey1vlb20Jkpc2VSKa7qpdQ4s2di4q7vZh0Ucoa9gQl5qZYHatDbmdU9weZVm2J+pQLPdE8KGbcP1Ll5KsnmcWCb/MOxQ8Wc7LCHm/lUoZXWro6H/gbPFgAjkmdWN2ss4H3y7OdiOkow+4zfbobxe9KFH2/QxXEynpWtQiEcknnZic0YImTFF6FH03x+ADC6/o4+Z/G56ReV8Cea79C+0IMdVJP96Ej0cjSXVSx9ou0QQaOjw41JAGpfG/o0lNKjHAJ5M5Xg09obO+kUwpR6pvFHKiwdbr5EaULkmwuX9hhs6LcOs4pnqjT4Qzj4bWkbF/Bag6oFNbyNtBp7I9sPoNmTXFvn5NJj81bLzqTfuyQg7mLknrmnn/r7xxQsElvkEoaWuwura0mKSCe//FXw8K1e22dEOEEUuQ7pEKLMFIX/90k15rjVbNhZQU4Ysozb9oLI45SdC8PtI2KBQ1VbeTZ7f4fCXTuXjfhIn13kRqyoljWqdpnYdXzU5amu3wiAGdPl1Fxlxuzd41nlFhg3f1MJGT43pGDebo38e0/dX2U3G8LgNRjf4FlzDbFDGAUb8K1fmXEd/DzTkH0IudXQGIu/lzeRjk=
  on:
    distributions: sdist bdist_wheel
    repo: gopinath-langote/1build
    branch: test-deployment
  server: https://test.pypi.org/legacy/
  skip_existing: true
  skip_cleanup: true
  